### ISSUE TITLE
non mod author deprecating mods

### ISSUE THREAD

**Issue by EIA485** [neos-modding-group/neos-mod-manifest#194] opened 2022-12-13 02:27 UTC
how should we handle situations where someone is deprecating someone else's mods,

 i think we should not deprecate a mod author's listing with out their approval

**Comment by XDelta** [comment] 2022-12-13 04:01
I would say that most mod creators should not be editing other mod entries that are not their own. Deprecation of a mod should be primarily up to the owner of the mod repo.

**Comment by ljoonal** [comment] 2022-12-18 12:41
My opinion is that usually only owners of mods should always be allowed to deprecate them. Or if as a modding community we have a strong consensus & agreement that something isn't being maintained and has issues.

In this specific case, I don't really see why it would be force deprecated, as the description pretty clearly summarizes the difference. Generally I believe things can just be talked out, so I'd want to hear @KyuubiYoru's thoughts on if there'd be a better way to resolve this, or if they'd be fine with marking it as deprecated :)

**Comment by KyuubiYoru** [comment] 2022-12-18 17:18
> It's a fork of my own mod that didn't even remove the patch that was very specifically there to try to coax the engine into using LibVLC. It's also listed higher than my own mod. I want to deprecate it. If you don't want to deprecate it, I'd be fine with having forks listed underneath their parent mods, but having a fork with faulty code being listed higher than my own mod has frustrated me for awhile.

I apologize for any frustration my fork of your mod may have caused you. I understand your desire to deprecate it, and I am fully supportive of that decision. I had originally created the fork with the intention on fixing constant crashesI had, caused by libvlc.

**Comment by ljoonal** [comment] 2022-12-19 20:56
At least this still holds 😄 

> Generally I believe things can just be talked out

I'd consider this now resolved, so closing the issue, as the related PR with the deprecation was merged due/with author acceptance :)

For the future, to consider this issue fully resolved, I'd advice opening communication between those involved should as the first option (possibly even just on the modding discord for example, although this issue tracker works too), with possibly the help of more neutral peeps if there's more clear disagreement/etc.

**Closed by ljoonal** 2022-12-19 20:56 UTC
Labels: conversation
